---
# =======================================================
# FASE 1: Containers aanmaken en starten op Proxmox
# =======================================================
- name: Uitrollen van LXC Containers op Proxmox
  hosts: proxmox
  gather_facts: false
  tasks:
    - name: Maak de LXC containers aan op Proxmox
      community.proxmox.proxmox:
        api_host: "{{ ansible_host }}"
        validate_certs: false
        api_user: "root@pam"
        api_password: "Alain!123"
        node: "Vm1"
        vmid: "{{ item.vmid }}"
        hostname: "{{ item.name }}"
        ostemplate: "local:vztmpl/debian-12-turnkey-wordpress_18.2-1_amd64.tar.gz"
        cores: 2
        memory: 2048
        disk: "vm-pool:16"
        unprivileged: true
        features:
          - nesting=1
        netif:
          net0: "name=eth0,bridge=vmbr0,ip={{ item.ip }}/24,gw=10.24.20.1"
        pubkey: "{{ lookup('file', '/root/.ssh/Ansible_VM.pub') }}"
        state: present
      loop:
        - { vmid: 120, name: 'wp-site-1', ip: '10.24.20.120' }
        - { vmid: 121, name: 'wp-site-2', ip: '10.24.20.121' }
        - { vmid: 122, name: 'wp-site-3', ip: '10.24.20.122' }
        - { vmid: 123, name: 'wp-site-4', ip: '10.24.20.123' }

    - name: Start de containers
      community.proxmox.proxmox:
        api_host: "{{ ansible_host }}"
        validate_certs: false
        api_user: "root@pam"
        api_password: "Alain!123"
        node: "Vm1"
        vmid: "{{ item.vmid }}"
        state: started
      loop:
        - { vmid: 120 }
        - { vmid: 121 }
        - { vmid: 122 }
        - { vmid: 123 }

    - name: Wacht totdat SSH actief is op alle 4 de nieuwe containers
      wait_for:
        host: "{{ item.ip }}"
        port: 22
        state: started
        timeout: 60
      loop:
        - { ip: '10.24.20.120' }
        - { ip: '10.24.20.121' }
        - { ip: '10.24.20.122' }
        - { ip: '10.24.20.123' } 
