[proxmox]
proxmox-server ansible_host=10.24.20.2 ansible_user=root ansible_ssh_private_key_file=/root/.ssh/Ansible_VM

[wordpress_containers]
wp-site-1 ansible_host=10.24.20.120 ansible_user=root ansible_ssh_private_key_file=/root/.ssh/Ansible_VM proxmox_vmid=120
wp-site-2 ansible_host=10.24.20.121 ansible_user=root ansible_ssh_private_key_file=/root/.ssh/Ansible_VM proxmox_vmid=121
wp-site-3 ansible_host=10.24.20.122 ansible_user=root ansible_ssh_private_key_file=/root/.ssh/Ansible_VM proxmox_vmid=122
wp-site-4 ansible_host=10.24.20.123 ansible_user=root ansible_ssh_private_key_file=/root/.ssh/Ansible_VM proxmox_vmid=123

[wordpress_containers:vars]
ansible_user=root
ansible_ssh_private_key_file=/root/.ssh/Ansible_VM

[monitoring]
grafana-server ansible_host=10.24.20.10 ansible_user=root ansible_ssh_private_key_file=/root/.ssh/Ansible_VM

[monitor_container]
vm-monitor ansible_host=10.24.20.222 ansible_user=root ansible_ssh_private_key_file=/root/.ssh/Ansible_VM